stages:
  - test
  - build_docker_image

variables:
  IMAGE_TAG_FILE: ${CI_PROJECT_DIR}/docker/versions.properties
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

.docker_image:
  image: docker:23.0.6
  tags:
    - dind
  services:
    - docker:dind
  before_script:
    - echo "Building UniFire docker image"
    - docker --version
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - export UNIFIRE_IMAGE_TAG=$(grep -E "^UNIFIRE_DOCKER_IMAGE_VERSION=" "${IMAGE_TAG_FILE}" | cut -d '=' -f 2)
    - echo "UniFire image tag will be = ${UNIFIRE_IMAGE_TAG}"
    - CONTAINER_IMAGE=${CI_REGISTRY_IMAGE}:${UNIFIRE_IMAGE_TAG}

.mvn:
  image: maven:3.8.2-openjdk-17-slim
  before_script:
    - java --version
    - mvn --version

test:
  extends: .mvn
  stage: test
  script:
    - mvn clean verify

python-test:
  stage: test
  image: ubuntu:24.04
  before_script:
    - apt-get update && apt-get install -y python3-pip python3 python3-lxml
    - python3 --version
    # flag is required to force system-wide installation (not in virtualenv)
    - pip install https://github.com/etetoolkit/ete/archive/ete4.zip --break-system-packages
  script:
    - cd ${CI_PROJECT_DIR}/misc/taxonomy
    - python3 -m unittest discover -s tests

build_docker_image_lite:
  stage: build_docker_image
  extends: .docker_image
  script:
    - CONTAINER_IMAGE=${CONTAINER_IMAGE}-lite
    - echo "image name will be ${CONTAINER_IMAGE}"
    - docker build --target lite -t ${CONTAINER_IMAGE} --no-cache docker
    - docker image ls
    - docker push ${CONTAINER_IMAGE}
    - docker rmi ${CONTAINER_IMAGE}
    - docker logout "$CI_REGISTRY"
  rules:
    - if: $CI_COMMIT_BRANCH == "pre_release" && $CI_COMMIT_TITLE =~ /^Merge branch '.*' into 'pre_release'$/
      when: on_success

build_docker_image_full:
  stage: build_docker_image
  extends: .docker_image
  script:
    - echo "image name will be ${CONTAINER_IMAGE}"
    - docker build --target full -t ${CONTAINER_IMAGE} --no-cache docker
    - docker image ls
    - docker push ${CONTAINER_IMAGE}
    - docker rmi ${CONTAINER_IMAGE}
    - docker logout "$CI_REGISTRY"
  rules:
    - if: $CI_COMMIT_BRANCH == "pre_release" && $CI_COMMIT_TITLE =~ /^Merge branch '.*' into 'pre_release'$/
      when: on_success

