# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - build_dependency
  - test
  - build_docker_image

include:
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  # - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.latest.gitlab-ci.yml
  - component: $CI_SERVER_FQDN/uniprot/aa/ci-components/library-release@master
    inputs:
      production_branches: "master"
      maven_cli_opts: "-P release"


variables:
  IMAGE_TAG_FILE: "${CI_PROJECT_DIR}/docker/versions.properties"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ''
  GITLAB_ADVANCED_SAST_ENABLED: 'true'
  DS_ENFORCE_NEW_ANALYZER: 'true'
  DS_MAX_DEPTH: "-1"
  GIT_DEPTH: "0"
  SECRET_DETECTION_HISTORIC_SCAN: "true"


.mvn:
  image: maven:3.8.2-openjdk-17-slim
  before_script:
    - java --version
    - mvn --version

build:
  extends: .mvn
  # Running in the build stage ensures that the dependency-scanning job
  # receives the maven.graph.json artifacts.
  stage: build_dependency
  script:
    - mvn install
    - mvn org.apache.maven.plugins:maven-dependency-plugin:3.8.1:tree -DoutputType=json -DoutputFile=maven.graph.json
  # Collect all maven.graph.json artifacts and pass them onto jobs
  # in sequential stages.
  artifacts:
    paths:
      - "**/*.jar"
      - "**/maven.graph.json"
  rules: &trigger_rules
    # Run on MR events: opened, new commits pushed to the source branch, reopened, etc.
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    # Prevent duplicate branch pipelines when an MR already exists for the branch
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    # Allow branch pipelines only when no open MR exists
    - if: '$CI_COMMIT_BRANCH'

test:
  extends: .mvn
  stage: test
  script:
    - mvn clean verify
  rules: *trigger_rules

python-test:
  stage: test
  image: ubuntu:24.04
  before_script:
    - apt-get update && apt-get install -y python3-pip python3 python3-lxml
    - python3 --version
    # flag is required to force system-wide installation (not in virtualenv)
    - pip install https://github.com/etetoolkit/ete/archive/ete4.zip --break-system-packages
  script:
    - cd ${CI_PROJECT_DIR}/misc/taxonomy
    - python3 -m unittest discover -s tests
  rules: *trigger_rules

.docker_image:
  image: docker:24.0.5
  tags:
    - dind
  services:
    - docker:24.0.5-dind
  before_script:
    - echo "Building UniFire docker image"
    - docker --version
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - export UNIFIRE_IMAGE_TAG=$(grep -E "^UNIFIRE_DOCKER_IMAGE_VERSION=" "${IMAGE_TAG_FILE}" | cut -d '=' -f 2)
    - echo "UniFire image tag will be = ${UNIFIRE_IMAGE_TAG}"

.build_docker_image_template:
  stage: build_docker_image
  extends: .docker_image
  script:
    - CONTAINER_IMAGE=${CI_REGISTRY_IMAGE}:${UNIFIRE_IMAGE_TAG}
    - export IMAGE_NAME=${CONTAINER_IMAGE}${IMAGE_SUFFIX}
    - echo "Building image ${IMAGE_NAME}"
    - docker build --target ${DOCKER_TARGET} --tag ${IMAGE_NAME} --no-cache docker
    - docker image ls
    - docker push ${IMAGE_NAME}
    - docker rmi ${IMAGE_NAME}
    - docker logout "$CI_REGISTRY"
  rules:
    - if: $CI_COMMIT_BRANCH == "pre_release" && $CI_COMMIT_TITLE =~ /^Merge branch '.*' into 'pre_release'$/
      when: on_success

build_docker_image_lite:
  extends: .build_docker_image_template
  variables:
    DOCKER_TARGET: lite
    IMAGE_SUFFIX: -lite

build_docker_image_full:
  extends: .build_docker_image_template
  variables:
    DOCKER_TARGET: full
    IMAGE_SUFFIX: ""
