<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~  Copyright (c) 2018 European Molecular Biology Laboratory
  ~
  ~  Licensed under the Apache License, Version 2.0 (the "License");
  ~  you may not use this file except in compliance with the License.
  ~  You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing, software
  ~  distributed under the License is distributed on an "AS IS" BASIS,
  ~  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~  See the License for the specific language governing permissions and
  ~  limitations under the License.
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>unifire</artifactId>
        <groupId>uk.ac.ebi.uniprot.aa</groupId>
        <version>${revision}</version>
        <relativePath>..</relativePath>
    </parent>

    <artifactId>unifire-distribution</artifactId>

    <properties>
        <revision>3.0-SNAPSHOT</revision>
        <commons-cli.version>1.5.0</commons-cli.version>
        <maven-assembly-plugin.version>2.5.5</maven-assembly-plugin.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>uk.ac.ebi.uniprot.aa</groupId>
            <artifactId>unifire-core</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.ac.ebi.uniprot.aa</groupId>
            <artifactId>unifire-engine</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.ac.ebi.uniprot.aa</groupId>
            <artifactId>unifire-io</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.ac.ebi.uniprot.aa</groupId>
            <artifactId>unifire-procedures</artifactId>
        </dependency>
        <dependency>
            <groupId>commons-cli</groupId>
            <artifactId>commons-cli</artifactId>
            <version>${commons-cli.version}</version>
        </dependency>

        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
        </dependency>

        <dependency>
            <groupId>org.fusesource.jansi</groupId>
            <artifactId>jansi</artifactId>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.xmlunit/xmlunit-core -->
        <dependency>
            <groupId>org.xmlunit</groupId>
            <artifactId>xmlunit-core</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>javax.xml.bind</groupId>
                    <artifactId>jaxb-api</artifactId>
                </exclusion>
            </exclusions>
            <scope>test</scope>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.xmlunit/xmlunit-matchers -->
        <dependency>
            <groupId>org.xmlunit</groupId>
            <artifactId>xmlunit-matchers</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>${maven-assembly-plugin.version}</version>
                <configuration>
                    <descriptors>
                        <descriptor>${project.basedir}/src/assembly/unifire_dist_assembly.xml</descriptor>
                    </descriptors>
                    <finalName>unifire</finalName>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>org/drools/compiler/**/*</exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>